import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// First-pass sidebar: list the existing docs in a sensible order.
// We'll split user_guide.md into sub-pages later (per spec §11 open question).
const sidebars: SidebarsConfig = {
  mainSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: ['user_guide'],
    },
    {
      type: 'category',
      label: 'Architecture',
      collapsed: false,
      link: {type: 'doc', id: 'architecture/overview'},
      items: [
        {type: 'autogenerated', dirName: 'architecture'},
      ],
    },
    {
      type: 'category',
      label: 'Developer Guide',
      collapsed: false,
      items: ['developer_guide'],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      items: ['api_reference', 'physics_notes'],
    },
  ],
};

export default sidebars;
