import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// First-pass sidebar: list the existing docs in a sensible order.
// We'll split user_guide.md into sub-pages later (per spec §11 open question).
const sidebars: SidebarsConfig = {
  mainSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: ['user_guide'],
    },
    {
      type: 'category',
      label: 'Architecture',
      collapsed: false,
      // No `link` here — _category_.json provides the generated-index landing.
      // Setting `link` would double-list overview.md as both category landing
      // AND first item, breaking prev/next pagination (overview → itself).
      items: [
        {type: 'autogenerated', dirName: 'architecture'},
      ],
    },
    {
      type: 'category',
      label: 'Developer Guide',
      collapsed: false,
      items: ['developer_guide'],
    },
    {
      type: 'category',
      label: 'Physics & Math',
      collapsed: false,
      items: [
        {type: 'autogenerated', dirName: 'physics'},
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      items: ['api_reference', 'physics_notes'],
    },
  ],
};

export default sidebars;
